### ISSUE TITLE
Completed surveys on deadline date are posing an issue with the next day Status update

### ISSUE THREAD

**Issue by aclowery** [bcgov/NewJobSurveyAdmin#101]
For employees who complete their survey on the deadline date (currently Friday). During the next day (Saturday) update, their status was temporarily made SurveyComplete and then immediately changed to Expired. 

Note that each day following has been going from expired to complete and complete back to expired.

This status should be made SurveyComplete if they have completed the survey (and not be changed), else it should be Expired.

**Comment by karmour** [comment]
This issue appears to still be active -- in my smoke testing in DEV for the Keycloak migration work, I was testing to see if a changed status in NJSA would still be pushed to Callweb. I changed an Expired status to Active and then completed the survey in Callweb, expecting the status to revise upon next refresh to SurveyComplete. However, the status in NJSA (and therefore pushed to Callweb) is Expired. Further, I'm seeing daily entries in the Timeline of the status switching to SurveyComplete and then back to Expired. So it's trying to update but hitting some kind of logic loop.

**Comment by aclowery** [comment]
@hangler could you check to see if there's a difference in PROD from DEV for this? It seems to me this issue is no longer relevant on PROD. When this issue was initially noticed in late 2021, I manually updated the status from Expired to SurveyComplete for individuals where this happened. However, I haven't needed to do that for records from 2022 which leads me to believe that there was a fix deployed.

**Comment by hangler** [comment]
This should be fixed again on dev. Fingers crossed!

**Comment by karmour** [comment]
Looks good to me now!

**Comment by aclowery** [comment]
This should be fixed, but will have confirmation tomorrow morning.

**Comment by karmour** [comment]
Confirming that our overnight test was successful and the morning Refresh Statuses task pulled in survey completion data from Callweb to set the status to SurveyComplete. This bug looks to be fully quashed again!
