### ISSUE TITLE
Update RefreshStatuses process to only refresh non-final states (i.e., Active status)

### ISSUE THREAD

**Issue by aclowery** [bcgov/NewJobSurveyAdmin#102]
Currently, RefreshStatuses is checking for all Expired or Active statuses and proceeding to refresh. No Expired statuses will be refreshed during this process and therefore just Active statuses being refreshed is required.

**Comment by hangler** [comment]
Urgency: low. Importance: medium. Should reduce load on the CallWeb API.

**Comment by aclowery** [comment]
_Survey: Expired_ does not need to be checked each day but it currently is... They cannot physically access a survey with that status, so I have to change to _Active_ first before anyhow before it could change to _Survey: Complete_. 

Related, I think that the only non-active status that may need to change (which I don't think it is currently doing this) is _Survey: Complete_, it's possible that we are requested to wipe responses. I wonder if we agreed that I would change the status manually when discussing this in the past...? Do you recall?

**Comment by hangler** [comment]
@aclowery is this the case for Exit Survey Admin too? We're checking "Expired" there as well... it's taking quite a bit of processing time.

**Comment by aclowery** [comment]
It likely is the case with Exit as well then. I only really noticed because the logs for NJSA are more descriptive, with the RefreshStatuses task displaying the number it checked e.g., "Tried to refresh 7216 employee statuses. 7216 were successful." Looking at the NJS data, it is the count of Active + Expired (+ the ones that were changed to Survey: Complete with the check). Exit has less information in the task log, so I wasn't exactly sure of the process, but if it is checking Expired statuses, it does not need to do so (in CallWeb at least). The Expired status is based on the # days defined in the Admin interface, so technically those could change.

**Comment by karmour** [comment]
Sorry to jump in, but the point about the expiration threshold in Admin being adjustable is probably why the system is checking Expired status upon refresh. If it wasn’t checking each time, then making a change to the expiry window would only affect those records which had not already expired, which may not be the desirable behaviour.

**Comment by hangler** [comment]
Let's continue discussion about Exit here: https://github.com/bcgov/ExitSurveyAdmin/issues/208

**Comment by aclowery** [comment]
An employee cannot access a survey when SURVEY_WINDOW_flag = 1. Which I believe the tool sets this value based on the status. That flag is empty for Active status and 1 with any other status.

**Comment by hangler** [comment]
@aclowery as we saw yesterday, this is no longer checking thousands of records.

Just to definitively address Kyle's point, however: let's say the admin adjusts the expiry threshold using the admin interface. This only affects employees added in the next batch, right? We're not retroactively adjusting anyone's survey dates, once they've already been added in (unless they had their blackout period set, and we're now turning off the blackout period). So we don't really need to examine expired employees.

Do I have that correct?

**Comment by hangler** [comment]
Discussed with @aclowery and it looks like I have it correct! In other words: modifying the times between reminders etc. is NOT retroactive.
