### ISSUE TITLE
Sometimes task run status does not update from "Running" on admin interface

### ISSUE THREAD

**Issue by hangler** [bcgov/NewJobSurveyAdmin#104]
Probably due to a timeout on the task.

Can we actually provide a more meaningful status update to the end user?

**Comment by aclowery** [comment]
This happened today when I had to trigger the 'Run Scheduled Task'. It still says 'Running..." but I received the emails that it parsed and loaded successfully (i.e., completed the task) so it should have changed by now.

**Comment by hangler** [comment]
This should now be fixed as of #105, which makes the task execution much faster.
