### ISSUE TITLE
Authorization is not restricted to the NewJobSurveyAdmin Keycloak role

### ISSUE THREAD

**Issue by danebenal** [bcgov/NewJobSurveyAdmin#107]
NJSA has several controllers which are restricted to authorized users with [Authorize]. This does not restrict the usage to users with the NewJobSurveyAdmin role, instead any IDIR user has full access to the application.

**Comment by hangler** [comment]
I went with a [policy-based approach](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1), so we could still inject the role name from the settings JSON. I believe this is what was originally intended.
