### ISSUE TITLE
LoadFromJSON taking longer than expected

### ISSUE THREAD

**Issue by aclowery** [bcgov/NewJobSurveyAdmin#115]
Typically, the LoadFromJSON takes 15 minutes maximum, but the last two Fridays have taken roughly 40 minutes. Investigation into why the time has increased significantly.

**Comment by aclowery** [comment]
Just noting that this has still been the case over the last two weeks.

**Comment by hangler** [comment]
This should be much faster now. @aclowery can you please verify? Thank you!

**Comment by aclowery** [comment]
On Tuesday, this appeared to take under a minute to run the scheduled task.

**Comment by hangler** [comment]
Great 😄
