### ISSUE TITLE
Save buttons are no longer working

### ISSUE THREAD

**Issue by aclowery** [bcgov/NewJobSurveyAdmin#132]
Can no longer update employee's statuses, or any of the fields on the Admin Interface. The saves don't get "locked in"; it remains on the Cancel/Save screen and is not allowing changes to be made. See image.
![image](https://github.com/bcgov/NewJobSurveyAdmin/assets/58310027/5a598e1b-561f-4fd6-9bf7-da573d2e7c0f)

**Comment by danebenal** [comment]
This has been resolved with changes from [commit 6f25055382c433f2bf82f522bb5cbdfe49b358ca](https://github.com/bcgov/NewJobSurveyAdmin/commit/6f25055382c433f2bf82f522bb5cbdfe49b358ca).

This issue was introduced with changes to the URL. The API Gateway does not appear to support lowercase post.
